@host = localhost:8000

// Access a Secured API Endpoint  
POST http://{{host}}/api/order HTTP/1.1 
content-type: application/json 
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QudXNlciIsImVtYWlsIjoidGVzdC51c2VyQGVtYWlsLmNvbSIsImV4cCI6MTY1MzU0NTUwNn0.TqMPVFc4CVjLDQttfdjDVeqQ1QiQ75tS0n5rj3Z67y0

{
    "seller_id" : 1,
    "item" : "Macbook Pro M1 Max (Space Gray)",
    "item_amount" : "2499",
    "weight" : "2.2kg"
}
###